version: '3.8'

networks:
  dev:
    driver: bridge
    
services:
  demo-app:
    image: docker.io/library/medicalminimalapiwebapi  
    build:
      context: ./Medical.MinimalAPI.WebAPI
      dockerfile: Dockerfile    
    container_name: demoapp-services
    ports:
      - "8088:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=admin;Host=host.docker.internal;Port=5432;Database=medicalDb;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - "app_db"
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    restart: always
    environment:
      POSTGRES_DB: medicalDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Medical.MinimalAPI.WebAPI/Scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  postgres-data:  